### ISSUE TITLE
[DISCUSSION] Logger (OS_Log) 사용

### ISSUE THREAD

**Issue by HenryVoid** [TheClimeet/climeet-iOS#30]
## 개요
- 디버깅, 트랙킹 시 Logger (OS_Log, Console)을 이용해보는 것은 어떨까요?

## 문제 상황
- 데이터 흐름을 추적하기 위한 장치가 없습니다.

## 고민 과정
- 디버깅 시 print를 이용하여 데이터 추적하는 것보다 console(app) 에 자동 작성되어 흐름을 따라가는 것이 편하지 않을까? 하는 고민에서 시작하였습니다.
- 중복호출, 화면이동, 데이터추적 등 여러가지 흐름을 순서대로 작성하여 분리한 상태에 따라 보여주는 console(app)을 따라가는 게 눈이 편할 것 같다.

## 해결 방안 제시
- Logger (OS_Log) 를 이용하여 Console (App)에서 흐름을 파악합니다.

**Comment by ericKwon95** [comment]
Logger의 도입 좋습니다!

저는 보통 아래와 같이 선언해서 사용하는데요, 혹시 우기님께서는 어떤 방식을 선호하시나요?

```swift
import OSLog

enum Constant {
  static let bundleID = Bundle.main.bundleIdentifier ?? ""
}

enum Logger {
  static let general = Logger(subsystem: Constant.bundleID, category: "general")
  // ...
}
```

**Comment by HenryVoid** [comment]
> Logger의 도입 좋습니다!
> 
> 저는 보통 아래와 같이 선언해서 사용하는데요, 혹시 우기님께서는 어떤 방식을 선호하시나요?
> 
> ```swift
> import OSLog
> 
> enum Constant {
>   static let bundleID = Bundle.main.bundleIdentifier ?? ""
> }
> 
> enum Logger {
>   static let general = Logger(subsystem: Constant.bundleID, category: "general")
>   // ...
> }
> ```

저도 다른게 없을 것 같습니다!
비슷한 방식으로 짜놓고 사용하고 있어요 ㅎㅎ

**Comment by iOS-Woong** [comment]
좋습니다!
현재는 Logger를
extension 으로 구성하여 네트워크 실패 케이스에서만 한정하여 표기되도록 사용하였었습니다.

```swift
import OSLog

extension Logger {
    
    private static var subsystem = Bundle.main.bundleIdentifier!
    
    // 네트워크 관련 로그
    static let networking = Logger(
        subsystem: subsystem,
        category: "networking"
    )
}
```

> 중복호출, 화면이동, 데이터추적 등 여러가지 흐름을 순서대로 작성하여 분리한 상태에 따라 보여주는 console(app)을 따라가는 게 눈이 편할 것 같다.

위 이유로 Logger를 도입한다는 의도 저도 좋은 것 같습니다!

**Comment by Ldoy** [comment]
확인이 늦어 죄송합니다! 저도 위에 논의하신 내용 대부분에 동의합니다 :) 👍
