### ISSUE TITLE
[DISCUSSION] 브랜치 프로텍션 룰셋 작성 건의

### ISSUE THREAD

**Issue by ericKwon95** [TheClimeet/climeet-iOS#34]
## 개요
- 클밋 iOS 브랜치 보호를 위한 룰셋 설정에 대한 건의입니다.

## 문제 상황
- 현재 클밋 iOS 브랜치에는 별다른 보호 룰셋이 없어, 실수가 발생할 가능성이 있습니다.
  - **Force Push**: 누군가 의도치 않게 과거 커밋을 덮어쓰는 실수가 발생할 수 있습니다.
  - **머지 과정**: 코드 리뷰 없이 머지가 진행되면 품질 저하나 버그 발생의 가능성이 커질 수 있습니다.

## 해결 방안 제시
- **Force Push 방지**: 모든 팀원이 실수로 기존 커밋을 덮어쓰는 위험을 방지하기 위해 Force Push를 금지하는 설정을 추가합니다.
- **Pull Request 기반 머지**: 코드 리뷰를 통한 검토 과정을 필수화해, 머지 전에 코드 품질을 확보합니다.
  - 최소 한 명 이상의 리뷰어가 승인을 해야 머지가 가능하도록 설정합니다.
- **CI/CD 통합 (선택 사항)**: 추가적으로, 빌드 또는 테스트가 실패한 경우 머지가 차단되도록 설정하여, 코드의 안정성을 더욱 강화할 수 있습니다.

## 기대 효과
- 실수로 인한 데이터 손실 및 코드 품질 저하를 사전에 방지할 수 있습니다.
- 팀원 간 코드 리뷰 프로세스를 정착시킴으로써, 코드 품질 향상과 더불어 협업의 효율성을 높일 수 있습니다.
- 협업 과정에서 발생할 수 있는 치명적인 실수를 방지하여, 장기적인 프로젝트 안정성을 확보할 수 있습니다.

## 추가 고려 사항
- 룰셋 도입 시 초기 적응 기간 동안 팀원들이 불편함을 느낄 수 있지만, 장기적인 프로젝트 관리와 협업 효율성을 생각할 때 긍정적인 결과를 기대할 수 있습니다.
- 룰셋의 세부 사항은 팀원들과의 협의를 통해 최종 결정하면 좋을 것 같습니다.

## 기타 사항
- 이 글은 chatGPT의 도움을 받아 작성되었습니다,,, ㅎㅎ

**Comment by HenryVoid** [comment]
혹시 포스푸시 가 주요 브랜치에만 걸 수도 있나요?
제가 자주 사용하긴 해서...
(ex. 커밋메시지 변경 후 재푸시, 리베이스 브랜치 재푸시 등)

**Comment by ericKwon95** [comment]
> 혹시 포스푸시 가 주요 브랜치에만 걸 수도 있나요? 제가 자주 사용하긴 해서... (ex. 커밋메시지 변경 후 재푸시, 리베이스 브랜치 재푸시 등)

넵 만약 적용하게 된다면 룰셋은 develop, main 등 주요 브랜치에만 적용할 계획입니다!
feature 등 하위 브랜치들은 적용하지 않을 계획이어서 괜찮을 것 같아요!

**Comment by iOS-Woong** [comment]
확인했습니다 기억하고있을게요!

1. ForcePush 금지
2. Pull Request 기반 머지 (*최소 한 명 이상의 리뷰어가 승인 후 머지)

+ 논의 CI/CD

**Comment by ericKwon95** [comment]
@Ldoy @iOS-Woong @HenryVoid 


### develop, main 브랜치에 대해 아래 규칙을 적용하였습니다.
- 허가 없는 브랜치 삭제 금지
- force push 금지
- 머지 이전 PR 필수
  - 최소 1명의 approve 필수
  - approve 이후 새로운 커밋이 발생했다면 새로운 approve 필요
 
궁금하신 점이나 변경하고 싶으신 점 있으시면 자유롭게 알려주세요~!
